news/urls.py
from django.urls import path

from news import views

urlpatterns = [
    path('news/', views.PostList.as_view(), name='news'),
    path('news/<slug:slug>/', views.PostDetail.as_view(), name='news_detail'),
]

office/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('offices/', views.OfficeList.as_view(), name='offices'),
]

order/urls.py
from django.urls import path

from order.views import order, thanks

urlpatterns = [
    path('order/', order, name='order'),
    path('thanks/', thanks, name='thanks'),
]

tracking/urls.py
from django.urls import path

from tracking.views import Search

urlpatterns = [
    path('search/', Search.as_view(), name='search'),
]

calculator/models.py
from django.db import models

# Create your models here.
class Calculate(models.Model):
    cityto = models.CharField(max_length=255, blank=False)
    cityfrom = models.CharField(max_length=255, blank=False)
    weightto = models.CharField(max_length=255, blank=False, default='')
    weightfrom = models.CharField(max_length=255, blank=False, default='')
    inter_terminal = models.CharField(max_length=255, blank=False)
    pickup = models.CharField(max_length=255, blank=False)
    cargo_delivery = models.CharField(max_length=255, blank=False)
    premium = models.CharField(max_length=255, blank=False)
    
    def __str__(self):
        return self.cityto



class Term(models.Model):
    cityto = models.CharField(max_length=255, blank=False)
    cityfrom = models.CharField(max_length=255, blank=False)
    term_standart_to = models.CharField(max_length=255, blank=False)
    term_standart_from = models.CharField(max_length=255, blank=False)
    term_express_to = models.CharField(max_length=255, blank=False)
    term_express_from = models.CharField(max_length=255, blank=False)

    def __str__(self):
        return self.cityto

news/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Post(models.Model):

    STATUS = (
        (0, 'Не опубликован'),
        (1, 'Опубликован')
    )
    title = models.CharField('Заголовок', max_length=200)
    slug = models.SlugField('URL', max_length=200, unique=True)
    text = models.TextField('Основной текст', max_length=10000)
    updated_on = models.DateTimeField(auto_now= True)
    created_on = models.DateTimeField('Дата публикации', default=timezone.now)
    status = models.IntegerField('Статус', choices=STATUS, default=0)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_on']   
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости' 
        

office/models.py
from django.db import models


# Create your models here.

class Office(models.Model):
    city = models.CharField('Город', max_length=10000)
    text = models.TextField('Основной текст', max_length=10000)


    def __str__(self):
        return self.city

    class Meta:
        verbose_name = 'Офис'
        verbose_name_plural = 'Офисы' 

order/models.py
from django.db import models

# Create your models here.

tracking/models.py
from django.db import models

# Create your models here.

calculator/forms.py
from django import forms
from calculator.models import Calculate, Term

class CalcForm(forms.ModelForm):
    class Meta:
        model = Calculate
        fields = '__all__'



class TermForm(forms.ModelForm):
     class Meta:
         model = Term
         fields = '__all__'

order/forms.py
from django import forms
from django.forms.widgets import Textarea, CheckboxInput

from consignment.models import OrderConsignment


class DateInput(forms.DateInput):
    input_type = 'date'


class OrderForm(forms.ModelForm):
    nature_cargo = forms.CharField(label='Характер груза',
                                   help_text='Грузы подлежащие обязательной упаковке могут быть приняты к перевозке '
                                             'без услуги "Упаковка" в случае наличия у отправителя надлежащей '
                                             'заводской '
                                             'упаковки, в противном случае груз не будет принят к перевозке')
    return_of_accompanying_documents = forms.BooleanField(label='Возврат сопроводительных документов',
                                                          help_text='Стоимость услуги 250 рублей', required=False)
    sending_accompanying_documents = forms.BooleanField(label='Отправка сопроводительных документов',
                                                        help_text='Стоимость услуги 50 рублей', required=False)
    delivery_confirmation = forms.BooleanField(label='Подтверждение доставки',
                                               help_text='Стоимость услуги 125 рублей', required=False)
    rigid_packaging = forms.BooleanField(label='Жесткая упаковка',
                                         help_text='Стоимость упаковки: 600 рублей за м3, минимальная стоимость '
                                                   '— 600 руб.', required=False)
    pallet_board = forms.BooleanField(label='Паллетный борт',
                                      help_text='Стоимость упаковки: 600 рублей за м3, минимальная стоимость '
                                                '— 600 руб.', required=False)
    bag = forms.BooleanField(label='Мешок',
                             help_text='Грузоподъемность одного мешка не более 25 кг. Стоимость упаковки: 80 '
                                       'рублей за единицу.', required=False)
    cardboard_box = forms.BooleanField(label='Картонная коробка',
                                       help_text='Размеры и стоимости коробок:'
                                                 '1. 0,2 х 0,19 х  0,13 м, вес груза до 2 кг- 40 рублей за штуку'
                                                 '2. 0,3 х 0,25 х 0,17 м, вес груза до 5 кг- 70 рублей за штуку'
                                                 '3. 0,3 х 0,26 х 0,38 м, вес до 12 кг- 100 рублей за штуку'
                                                 '', required=False)
    pallet = forms.BooleanField(label='Палет',
                                help_text='Стоимость: 160 рублей за паллет.', required=False)
    strapping = forms.BooleanField(label='Стреппинг',
                                   help_text='Стоимость: 100 рублей за м3, минимальная стоимость — 100 руб.',
                                   required=False)
    stretch = forms.BooleanField(label='Стрейч - пленка',
                                 help_text='Стоимость упаковки: 150 рублей за м3, минимальная стоимость — 150 руб.',
                                 required=False)
    air_bubble = forms.BooleanField(label='Воздушно - пузырьковая пленка',
                                    help_text='Стоимость упаковки: 150 рублей за м3, минимальная стоимость — 150 руб.',
                                    required=False)

    class Meta:
        model = OrderConsignment
        fields = '__all__'
        widgets = {
            'date_cargo': DateInput(), 'comment': Textarea(), 'sender_payer': CheckboxInput(attrs={'class': 'as'}),
            'recipient_payer': CheckboxInput(attrs={'class': 'as'}),
            'sender_customer': CheckboxInput(attrs={'class': 'as1'}),
            'recipient_customer': CheckboxInput(attrs={'class': 'as1'}),
        }

calculator/views.py
from django.shortcuts import render
from django.http.response import JsonResponse

from rest_framework import status
from rest_framework.parsers import JSONParser 
from rest_framework.decorators import api_view

from calculator.models import Calculate, Term
from calculator.serializers import CalculateSerializer, TermSerializer

import json
# Create your views here.

def calc(request):

    context = { 
        'is_worker': request.user.groups.filter(name='worker').exists(),
    }
    
    return render(request, 'calculator.html', context)


def calc_post(request):
    struct = request.POST.get('struct')
    weight = float(struct[3])
    volume = float(struct[4])
    volume_weight = volume * 240
    max_weight = max(weight, volume_weight)
    
    response = Calculate.objects.filter(cityto__exact=struct[0]).filter(cityfrom__exact=struct[1]).filter(weightto__gte=str(max_weight))
    #response_term = Term.objects.filter(cityto__exact=struct[0]).filter(cityfrom__exact=struct[1]).filter
    res_calc = {
        'cityto': response[0][0],
        'cityfrom': response[0][1],    
        'weightto': response[0][2],  
        'weightfrom': response[0][3],
        'inter_terminal': response[0][4],
        'pickup': response[0][5],
        'cargo_delivery': response[0][6],
    }

    return json.dumps(res_calc)


@api_view(['GET', 'POST'])
def create_calculate(request):  
    if request.method == 'GET':
        calc_api = Calculate.objects.all()
        calc_api_serializer = CalculateSerializer(calc_api, many=True)
        return JsonResponse(calc_api_serializer.data, safe=False)

    elif request.method == 'POST':
        calc_api_data = JSONParser().parse(request)
        calc_api_serializer = CalculateSerializer(data=calc_api_data, many=True)
        if calc_api_serializer.is_valid():
            calc_api_serializer.save()
            return JsonResponse(calc_api_serializer.data, safe=False, status=status.HTTP_201_CREATED)
        return JsonResponse(calc_api_serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['PUT'])
def update_calculate(request, pk):
    try:
        calc_api = Calculate.objects.get(pk=pk)
    except Calculate.DoesNotExist:
        return JsonResponse({'message': 'Накладной не существует'}, status=status.HTTP_404_NOT_FOUND)

    if request.method == 'PUT':
        calc_api_data = JSONParser().parse(request)
        calc_api_serializer = CalculateSerializer(calc_api, data=calc_api_data)
        if calc_api_serializer.is_valid():
            calc_api_serializer.save()
            return JsonResponse(calc_api_serializer.data, safe=False, status=status.HTTP_201_CREATED)
        return JsonResponse(calc_api_serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'POST'])
def create_term(request):  
    if request.method == 'GET':
        term_api = Term.objects.all()
        term_api_serializer = TermSerializer(term_api, many=True)
        return JsonResponse(term_api_serializer.data, safe=False)

    elif request.method == 'POST':
        term_api_data = JSONParser().parse(request)
        term_api_serializer = TermSerializer(data=term_api_data, many=True)
        if term_api_serializer.is_valid():
            term_api_serializer.save()
            return JsonResponse(term_api_serializer.data, safe=False, status=status.HTTP_201_CREATED)
        return JsonResponse(term_api_serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['PUT'])
def update_term(request, pk):
    try:
        term_api = Term.objects.get(pk=pk)
    except Term.DoesNotExist:
        return JsonResponse({'message': 'Накладной не существует'}, status=status.HTTP_404_NOT_FOUND)

    if request.method == 'PUT':
        term_api_data = JSONParser().parse(request)
        term_api_serializer = TermSerializer(term_api, data=term_api_data)
        if term_api_serializer.is_valid():
            term_api_serializer.save()
            return JsonResponse(term_api_serializer.data, safe=False, status=status.HTTP_201_CREATED)
        return JsonResponse(term_api_serializer.errors, status=status.HTTP_400_BAD_REQUEST)

news/views.py
from django.views import generic

from news.models import Post
# Create your views here.

class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'news.html'


class PostDetail(generic.DetailView):
    model = Post
    template_name = 'news_detail.html'

office/views.py
from django.views import generic

from office.models import Office

class OfficeList(generic.ListView):
    queryset = Office.objects.all()
    template_name = 'offices.html'

order/views.py
import json

from django.shortcuts import redirect, render

from order.forms import OrderForm

from calculator.models import Calculate

# Create your views here.


def order(request):
    form = OrderForm()
    if request.method == "POST":
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('thanks')
    return render(request, 'order.html', {'form': form})


def thanks(request):
    context = {
         'is_worker': request.user.groups.filter(name='worker').exists(),
    }
    return render(request, 'thanks.html', context)


def my_data(request):
    data = json.loads(request.body)
    max_weight = max(data[2], data[3]*240)
    response = Calculate.objects.filter(cityto__exact=data[0]).filter(cityfrom__exact=data[1]).filter(weightto__gte=max_weight).filter(weightfrom__lte=max_weight)
    res_order = {
        'my_data': response
    }
    return json.dumps(res_order)

tracking/views.py
from django.shortcuts import render
from django.views.generic.list import ListView

from consignment.models import TrackStatusConsignment

# Create your views here.

class Search(ListView):
    model = TrackStatusConsignment()
    template_name = 'tracking.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = TrackStatusConsignment.objects.filter(tracking_number__icontains=query)

        return object_list

templates/404_page.html
{% load static %}

<link rel="stylesheet" href="{% static '/css/404_page.css' %}">

<head>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@600;900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/4b9ba14b0f.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="mainbox">
      <div class="err">4</div>
      <i class="far fa-question-circle fa-spin"></i>
      <div class="err2">4</div>
      <div class="msg">Страница ещё не существует!<p>Вернись на  <a href="{% url 'index' %}">главную</a>.</p></div>
        </div>

templates/block_button.html
{% load static %}


<header>
    <div class="overlay"></div>
    <img class="back" src="{% static '/img/back.jpg' %}" alt="">
    <div class="container h-100">
        <div class="d-flex h-50 text-center align-items-center">
            <div class="w-100 text-white">
                <h1 class="display-4 title text-uppercase">перевозка грузов, посылок, документов <br> по россии</h1>
            </div>
        </div>
        <div class="container row h-50 align-items-end">
            <div class="col">
                <div class="card-group position-relative">
                    <div class="card text-center" style="background-color: #3D3935;">
                        <a href="/calc/" target="_blank" style="color: inherit;">
                            <div class="card-body">
                                <img src="{% static '/img/calculate_icon.png' %}" alt="">
                                <p class="card-text text1 calc text-white">КАЛЬКУЛЯТОР</p>
                            </div>
                        </a>
                    </div>
                    <div class="card text-center" style="background-color: #3D3935;">
                        <a href="/order/" target="_blank" style="color: inherit;">
                            <div class="card-body " style=" border-left: 1px solid white;
                        border-right: 1px solid white">
                                <img src="{% static '/img/receipt_icon.png' %}" alt="">
                                <p class="card-text text1 text-white">РАСЧЕТ И ОФОРМЛЕНИЕ <br> ЗАКАЗА</p>
                            </div>
                        </a>
                    </div>
                    <div class="card text-center" style="background-color: #3D3935;">
                        <a href="/tracking/" target="_blank" style="color: inherit;">
                            <div class="card-body">
                                <img src="{% static '/img/map_icon.png' %}" alt="">
                                <p class="card-text text1 text-white">МЕСТОНАХОЖДЕНИЕ <br> ГРУЗА</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>



<h4 class="mb-4 text-center text-uppercase subtitle" style="margin-top: 55px;">Основные виды перевозок</h4>
<div class="container-fluid">
    <div class="row">
        <div class="col-xl">
            <div class="card-deck" style="margin-bottom: 75px;">
                <div class="card text-center">
                    <div class="card-body">
                        <h5 class="card-title text-uppercase text2">Стандарт</h5>
                        <p class="card-text text3">
                            Перевозка сборного <br> груза автомобильным <br> транспортом
                        </p>
                        <p class="card-text text4">
                            <a href="/standart/" target="_blank" style="color: #007041;">Узнать больше</a>
                        </p>
                    </div>
                </div>
                <div class="card text-center">
                    <div class="card-body">
                        <h5 class="card-title text-uppercase text2">Экспресс</h5>
                        <p class="card-text text3">
                            Ускоренная перевозка <br> грузов, сроком от <br> одного рабочего дня
                        </p>
                        <p class="card-text text4">
                            <a href="/ekspress/" target="_blank" style="color: #007041;">Узнать больше</a>
                        </p>
                    </div>
                </div>
                <div class="card text-center">
                    <div class="card-body">
                        <h5 class="card-title text-uppercase text2">Конверт</h5>
                        <p class="card-text text3">
                            Отправка документов <br> в фирменном <br> конверте
                        </p>
                        <p class="card-text text4">
                            <a href="/konvert/" target="_blank" style="color: #007041;">Узнать больше</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
</div>

templates/calculator.html
{% extends "shared/base.html" %} 
{% load static %}


{% block base_content %}
<h4 class="mb-4 text-center text-uppercase subtitle" style="margin-top: 55px;">Калькулятор</h4>
<div class="container">
    <div class="jumbotron">
    <form action="{% url 'calc' %}" method="POST" >
      {% csrf_token %}
        <div class="row mb-3">
            <div class="form-group col-md-6 col-sm-6">
                <p class="">Откуда</p>
                <input type="text" class="form-control" id="cityfrom" required="" />
            </div>
            <div class="form-group col-md-6 col-sm-6">
                <p class="">Куда</p>
                <input type="text" class="form-control"  id="cityto" required=""/>
            </div>
            <div class="form-group col-md-4 col-sm-6">
                <p class="">Кол-во мест</p>
                <input type="text"  class="form-control" id="quantity" required=""  />
            </div>
            <div class="form-group col-md-4 col-sm-6">
                <p class="">Вес груза</p>
                <input type="text" class="form-control" id="weight" required=""  />
            </div>
            <div class="form-group col-md-4 col-sm-6">
                <p class="">Объем</p>
                <input type="text"  class="form-control" id="volume" required=""/>
            </div>
    
            <div class="custom-control custom-checkbox">
            <div class="form-group form-check" style="visibility: visible;">
                <input type="checkbox" id="pickUp"  class="custom-control-input"/>
                <label class="custom-control-label" for="pickUp">Необходимо забрать груз с адреса</label>
            </div>
            <div class="form-group form-check" style="visibility: visible;">
                <input type="checkbox" id="delivery"  class="custom-control-input"/>
                <label class="custom-control-label" for="delivery">Необходимо доставить груз до адреса</label>
            </div>
            </div>

            <table class="table">
                <thead> 
                  <tr>
                    <th scope="col"></th>
                    <th scope="col">Стоимость</th>
                    <th scope="col">Срок</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">Стандарт</th>
                    <td id="standartCost"></td>
                    <td id="standartTerm"></td>
                  </tr>
                  <tr>
                    <th scope="row">Экспресс</th>
                    <td id="expressCost"></td>
                    <td id="expressTerm"></td>
                  </tr>
                </tbody>
              </table>
              
              <div class="col-md-12 col-12 ">
                <input type="button" style="background-color: #3D3935; border-color: #3D3935;"  id="btn" class="btn btn-primary btn-lg btn-block" value="Рассчитать" onclick="calc()"/>
              </div>
            </div>
              <div class="row mb-3"> 
              <div class="col-md-12 col-12 ">
               <a href="/order/" style="visibility: hidden; text-decoration: none; " target="_blank"> <input type="button" style="background-color: #3D3935; border-color: #3D3935;"  id="orderBtn" class="btn btn-primary btn-lg btn-block" value="Оформить заявку"/> </a>
              </div>
            </div>
    </form>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
    function calc(){
      let req = new XMLHttpRequest();
      let cityfrom = document.getElementById('cityfrom').value;
      let cityto = document.getElementById('cityto').value;
      let quantity = document.getElementById('quantity').value;
      let weight = document.getElementById('weight').value;
      let volume = document.getElementById('volume').value;
      let pickUp = document.getElementById('pickUp').checked;
      let delivery = document.getElementById('delivery').checked;

      let standartCost = document.getElementById('standartCost');
      let standartTerm = document.getElementById('standartTerm');
      let expressCost = document.getElementById('expressCost');
      let expressTerm = document.getElementById('expressTerm');
      
      let struct = {
        cityfrom: cityfrom,
        cityto: cityto,
        quantity: quantity,
        weight: weight,
        volume: volume,
        pickUp: pickUp,
        delivery: delivery
      };
      console.log(struct)

      if (cityto != '' && cityfrom != '' && quantity != '' && weight != '' && volume != ''){
        req.onload = function(){
          let res_calc = JSON.stringify(this.responseText);
          if (res_calc.inter_terminal){
            st_full = 0;
            ex_full = 0;
            if (pickUp == true){
              st_full = st_full + res_calc.pickup;
              ex_full = ex_full + res_calc.pickup;
            }
            if (delivery == true) {
              st_full = st_full + res_calc.cargo_delivery;
              ex_full = ex_full + res_calc.cargo_delivery;
            }

            st_full = st_full + res_calc.inter_terminal;
            ex_full = ex_full + res_calc.inter_terminal;

            standartCost.innerHTML = st_full + " р. ";
            standartTerm.innerHTML = 3 - 5;
            expressCost.innerHTML = ex_full + " р. ";
            expressTerm.innerHTML = 1 - 3;

          }
          
        }
        req.open('GET', '/calc/', struct, true);
        req.setRequestHeader('content-type', 'application/json; charset=UTF-8');
        req.send();
      }
    };

 
</script>


<style>
  .reveal{
    visibility: visible;
  }
</style>
{%endblock%}

templates/home.html
{% extends 'shared/base.html' %} {% block base_content %} {% include 'block_button.html' %} {% endblock %}

templates/news.html
{% extends "shared/base.html" %} 
{% load static %}
{% block base_content %}

<style>
    body {
        font-family: "Gotham Pro";
        font-size: 18px;
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: white;
    }
    
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
    .card-link{
        color: #007041;
    }
</style>

<h4 class="mb-4 text-center text-uppercase subtitle" style="margin-top: 55px;">Новости</h4>
<div class="container">
    <div class="row">
        
        <div class="col-xl">
            {% for post in post_list %}
     
                <div class="card mb-4">
                    <div class="card-body">
                        <h2 class="card-title">{{ post.title }}</h2>
                        <p class="card-text text-muted h6">{{ post.created_on}} </p>
                        <p class="card-text">{{post.text|slice:":1000" | safe}}</p>
                        <a href="{% url 'news_detail' post.slug  %}" class="card-link">Узнать больше &rarr;</a>
                    </div>
                </div>
            {% endfor %}
            
        </div>
    </div>
</div>
{%endblock%}

templates/news_detail.html
{% extends "shared/base.html" %} 
{% block base_content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.created_on }}</p>
        <p class="card-text ">{{ object.text | safe }}</p>
      </div>
    </div>
  </div>
</div>

{% endblock base_content %}

templates/offices.html
{% extends 'shared/base.html' %}
{% block base_content %}

<h4 class="mb-4 text-center text-uppercase subtitle" style="margin-top: 55px;">Офисы</h4>
<div class="container">
    <div class="row">
        
        <div class="col-xl">
            {% for office in office_list %}
     
                <div class="card mb-4">
                    <div class="card-body">
                        <h2 class="card-title">{{ office.city| safe }}</h2>
                        <p class="card-text">{{office.text| safe}}</p>
                    </div>
                </div>
            {% endfor %}
            
        </div>
    </div>
</div>
{% endblock base_content %}

templates/price.html
{% extends 'shared/base.html' %} 


{% block base_content %}  
<h4 class="mb-4 text-center text-uppercase subtitle" style="margin-top: 55px;">Прайс</h4>
<div class="container">
    <div class="mb-5">
        <ul class="list-group ">
            <li class="list-group-item"><a href="/static/t_lo.pdf" target="_blank" style="color: #007041;">Направление Ленинградская область</a></li>
            <li class="list-group-item"><a href="/static/t_petr.pdf"  target="_blank" style="color: #007041;">Направление Петрозаводск</a></li>
            <li class="list-group-item"><a href="/static/t_pskov_nov.pdf"  target="_blank" style="color: #007041;">Направление Псков, Великий Новгород</a> </li>
        </ul>
    </div>
</div>


{% endblock %}

templates/reglog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <script src="https://kit.fontawesome.com/64d58efce2.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static '/css/reglog.css' %}">

    <title>Регистрация и Вход Гарант-Логистика</title>
</head>

<body>
<div class="container-reg-log">
    <div class="forms-container">
        <div class="signin-signup">
            <form action="#" method="POST" class="sign-in-form">
                {% csrf_token %}
                <h2 class="title">Вход</h2>
                <div class="input-field">
                    <i class="fas fa-user"></i>
                    <input type="text" name="login" placeholder="Логин"/>
                </div>
                <div class="input-field">
                    <i class="fas fa-lock"></i>
                    <input type="password" name="psw" placeholder="Пароль"/>
                </div>
                <div>
                    <i></i>
                    <label>
                        <input type="checkbox" name="remember" checked/> Запомнить меня
                    </label>
                </div>
                <input type="submit" value="Вход" class="btn solid"/>
                <p class="social-text">Или войдите с помощью сервисов</p>
                <div class="social-media">
                    <a href="#" class="social-icon">
                        <i class="fa fa-vk" aria-hidden="true"></i>
                    </a>
                    <a href="#" class="social-icon">
                        <i class="fab fa-google"></i>
                    </a>
                </div>
            </form>
            <form action="#" method="post" class="sign-up-form">
                {% csrf_token %}
                <h2 class="title">Регистрация</h2>
                <div class="input-field">
                    <i class="fas fa-user"></i>
                    <input type="text" name="login" placeholder="Логин"/>
                </div>
                <div class="input-field">
                    <i class="fas fa-envelope"></i>
                    <input type="email" name="email" placeholder="Email"/>
                </div>
                <div class="input-field">
                    <i class="fas fa-lock"></i>
                    <input type="password" name="psw" placeholder="Пароль"/>
                </div>
                <input type="submit" class="btn" value="Регистрация"/>
                <p class="social-text">Или войдите с помощью сервисов</p>
                <div class="social-media">
                    <a href="#" class="social-icon">
                        <i class="fa fa-vk" aria-hidden="true"></i>
                    </a>
                    <a href="#" class="social-icon">
                        <i class="fab fa-google"></i>
                    </a>
                </div>
            </form>
        </div>
    </div>

    <div class="panels-container">
        <div class="panel left-panel">
            <div class="content">
                <h3>Впервые здесь?</h3>
                <p>
                    Зарегистрируйтесь, чтбы получить доступ ко всем нашим сервисам!
                </p>
                <button class="btn transparent" id="sign-up-btn">
                    Регистрация
                </button>
            </div>
            <!--<img src="img/logo_small.jpg" class="image" alt="" />-->
        </div>
        <div class="panel right-panel">
            <div class="content">
                <h3>Уже регистрировались?</h3>
                <p>
                    Войдите в личный кабинет!
                </p>
                <button class="btn transparent" id="sign-in-btn">
                    Вход
                </button>
            </div>
            <!--<img src="img/register.svg" class="image" alt="" />-->
        </div>
    </div>

</div>
</body>

<script>
    const sign_in_btn = document.querySelector("#sign-in-btn");
const sign_up_btn = document.querySelector("#sign-up-btn");
const back_to_main_btn = document.querySelector("#back-to-main-btn")
const container = document.querySelector(".container-reg-log");

sign_up_btn.addEventListener("click", () => {
    container.classList.add("sign-up-mode");
});

sign_in_btn.addEventListener("click", () => {
    container.classList.remove("sign-up-mode");
});

</script>

</html>

templates/thanks.html
{% extends 'shared/base.html' %} 

{% block base_content %}  
<div class="container">
    <h4 class="font-weight-bold">Заявка отправлена успешно!</h4>
</div>
{% endblock %}